name: Docker Image Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      TERM: xterm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t sai40


      - name: Install Docker Scout
        run: |
          sudo apt update && sudo apt -y install curl
          mkdir -p ~/.docker/cli-plugins
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      - name: Run Docker Scout CVE Scan
        run: |
          docker scout cves archana > image-cves-scan.csv
          cat image-cves-scan.csv
          
      - name: Checking Image Overview
        run: |
          docker scout quickview archana > image-scan-overview.csv
          cat image-scan-overview.csv
         
      
